# .config/shell/aliases.sh

# Git
alias ga="git add"
alias gap="ga --patch"
alias gau="ga -u"
alias gb="git branch"
alias gbd="gb -d"
alias gbv="gb -a -vv"
alias gc="git commit"
alias gca="gc --amend --no-edit"
alias gco="git checkout"
alias gn="gco -b"
alias gcl="git clone"
alias gd="git diff --output-indicator-new=' ' --output-indicator-old=' '"
alias gds="gd --staged"
alias gf="git fetch"
alias gl="git log --graph --all --pretty='%C(magenta)%h %C(white) %an  %ar%C(auto)  %D%n%s%n'"
alias gm="git merge"
alias gp="git push"
alias gpd="gp -d"
alias gpf="gp -f"
alias gpu="gp -u"
alias grs="git reset"
alias grsh="grs --hard"
alias grsm="grs --mixed"
alias grss="grs --soft"
alias grma="git remote add"
alias grmv="git remote -v"
alias gs="git status --short"
alias gsm="git submodule"
alias gsmi="gsm update --init --recursive"
alias gsmu="gsm update --remote"
alias gu="git pull"
alias gw="git worktree"
alias gwa="gw add"
alias gwl="gw list"
alias gwr="gw remove"
